/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-01-29 18:04:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html lang=\"en\">  \r\n");
      out.write("<meta charset=\"utf-8\"/>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<head><title>Bootstrap Website Tutorial</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-3.2.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("/*************************NavBarStyling *****************************/\r\n");
      out.write("\r\n");
      out.write(".navbar{\r\n");
      out.write("margin-bottom: 0;\r\n");
      out.write("border-radius:0;\r\n");
      out.write("background-color: #5E4485;\r\n");
      out.write("color:#FFF;\r\n");
      out.write("padding:1% 0;\r\n");
      out.write("font-size:1.2em;\r\n");
      out.write("border:0;\r\n");
      out.write("}\r\n");
      out.write(".navbar-brand{\r\n");
      out.write("float: left;\r\n");
      out.write("min-height: 55 px;\r\n");
      out.write("padding:0 15px 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-nav .active a{\r\n");
      out.write("color:#FFF;\r\n");
      out.write("background-color:#5E4485;\r\n");
      out.write("}    \r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-nav .active a:focus{\r\n");
      out.write("color:#FFF;\r\n");
      out.write("background-color:#5E4485;\r\n");
      out.write("}\r\n");
      out.write(".navbar-inverse .navbar-nav .active a:hover{\r\n");
      out.write("color:#FFF;\r\n");
      out.write("background-color:#5E4485;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-inverse .navbar-toggle:hover {\r\n");
      out.write("    background-color: #5E4485;\r\n");
      out.write("    border:1.5px solid #FFF ;\r\n");
      out.write("}\r\n");
      out.write(".navbar-inverse .navbar-nav li a {\r\n");
      out.write("color: #D5D5D5;\r\n");
      out.write("}\r\n");
      out.write("/*************************NavBarStyling Ends*****************************/\r\n");
      out.write("/*************************CarouselStyling*****************************/\r\n");
      out.write(".carousel-caption{\r\n");
      out.write("top:50%;\r\n");
      out.write("transform:translateY(-50%);\r\n");
      out.write("text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("font-size:18px;\r\n");
      out.write("color:#FFF;\r\n");
      out.write("padding:12px 22px;\r\n");
      out.write("background-color: #5E4485;\r\n");
      out.write("border:2px solid #FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/*************************CarouselStyling Ends*****************************/\r\n");
      out.write(".container{\r\n");
      out.write("margin:4% auto;\r\n");
      out.write("}\r\n");
      out.write("#icon{\r\n");
      out.write("max-width:200px;\r\n");
      out.write("margin:1% auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("footer{\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#5E4485;\r\n");
      out.write("padding:5%;\r\n");
      out.write("color:#FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa{\r\n");
      out.write("padding:15px;\r\n");
      out.write("font-size:30px;\r\n");
      out.write("color:#FFF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa:hover{\r\n");
      out.write("color:#D5D5D5;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("/*For mobile version */\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 900px){\r\n");
      out.write(".fa{\r\n");
      out.write("font-size:20px;\r\n");
      out.write("padding:10px;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 600px){\r\n");
      out.write(".carousel-caption{\r\n");
      out.write("display:none;\r\n");
      out.write("\t}\r\n");
      out.write("#icon{\r\n");
      out.write("max-width:150px;\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("font-size:1.9em;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body> \r\n");
      out.write("<!-- *************************NavBar*****************************-->\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\" id=\"leftAlignedNavBar\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#MyNavBar\">\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"><img src=\"img/w3newbie.png\">  </a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"MyNavBar\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write(" \t\t\t<li class=\"active\"><a href=\"#\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">About</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Services</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Testimonials</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Contact</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav> \r\n");
      out.write("<!-- *************************NavBar Ends*****************************-->\r\n");
      out.write("<!-- *************************Slider *****************************-->\r\n");
      out.write("\t<div id=\"MyCarousel\" class=\"carousel slide \" data-ride=\"carousel\">\r\n");
      out.write("\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t<li data-target=\"#MyCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#MyCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t<li data-target=\"#MyCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t</ol>\r\n");
      out.write("\t\t<div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t<img src=\"img/mountains.png\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t<h1>get to know bootstrap</h1>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-default\" href=\"enquiry.jsp\">Get STarted</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> <!-- End Active --> \r\n");
      out.write("\t\t\t<div class =\"item\">\r\n");
      out.write("\t\t\t<img src=\"img/snow.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class =\"item\">\r\n");
      out.write("\t\t\t<img src=\"img/red.png\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- \t\tSlider control  -->\r\n");
      out.write("\t\t<a class=\"left carousel-control\" href=\"#MyCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<a class=\"right carousel-control\" href=\"#MyCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t<span class=\"sr-only\"></span>\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- **************Carousel Ends ******************** -->\r\n");
      out.write("\t<div class=\"container text-center\">\r\n");
      out.write("\t<h2>What we're using</h2>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"img/html5.png\" id=\"icon\">\r\n");
      out.write("\t\t\t<h4 class=\"text-center\">HTML5</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"img/bootstrap.png\" id=\"icon\">\r\n");
      out.write("\t\t\t<h4 class=\"text-center\">Bootstrap</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"img/css3.png\" id=\"icon\">\r\n");
      out.write("\t\t\t<h4 class=\"text-center\">CSS3</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<h4>Here is the cool thing about Bootstrap!!!</h4>\r\n");
      out.write("\t\t\t\t<p class=\"text-justify\">Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\tthe parent element, therefore the :hover pseudo class should be after .navbar-toggle \r\n");
      out.write("\t\t\t\tas opposed to the .icon-bar . In other words, you should use the selector .navbar-toggle:hover\r\n");
      out.write("\t\t\t\t .icon-bar .Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\t the parent element, therefore the :hover pseudo class should be after .navbar-toggle a\r\n");
      out.write("\t\t\t\t s opposed to the .icon-bar . In other words, you should use the selector \r\n");
      out.write("\t\t\t\t .navbar-toggle:hover .icon-bar .</p>\r\n");
      out.write("\t\t\t\t<p class=\"text-justify\">Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\tthe parent element, therefore the :hover pseudo class should be after .navbar-toggle \r\n");
      out.write("\t\t\t\tas opposed to the .icon-bar . In other words, you should use the selector .navbar-toggle:hover\r\n");
      out.write("\t\t\t\t .icon-bar .Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\t the parent element, therefore the :hover pseudo class should be after .navbar-toggle a\r\n");
      out.write("\t\t\t\t s opposed to the .icon-bar . In other words, you should use the selector \r\n");
      out.write("\t\t\t\t .navbar-toggle:hover .icon-bar .</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t<img src=\"img/bootstrap2.jpg\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t \t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4>Header1</h4>\r\n");
      out.write("\t\t\t\t<p>Sep 6, 2014 - You ar\r\n");
      out.write("\t\t\t\te wanting to change the background color when hovering over the parent element, \r\n");
      out.write("\t\t\t\ttherefore the :hover pseudo class should be after .navbar-toggle as opposed to the .icon-bar . \r\n");
      out.write("\t\t\t\tIn other words, you should use the selector .navbar-toggle:hover .icon-bar .\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"img/sass.png\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<h4>Header2</h4>\r\n");
      out.write("\t\t\t\t<p>Sep 6, 2014 - You ar\r\n");
      out.write("\t\t\t\te wanting to change the background color when hovering over the parent element, \r\n");
      out.write("\t\t\t\ttherefore the :hover pseudo class should be after .navbar-toggle as opposed to the .icon-bar . \r\n");
      out.write("\t\t\t\tIn other words, you should use the selector .navbar-toggle:hover .icon-bar .\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-3 col-sm-6 col-xs-12\">\r\n");
      out.write("\t\t\t\t<img src=\"img/less.png\" class=\"img-responsive\">\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<h4><a href=\"#hidden\" data-toggle=\"collapse\">Want to learn more about Bootstrap!!!</a></h4>\r\n");
      out.write("\t\t\t\t<div id=\"hidden\" class=\"collapse\">\r\n");
      out.write("\t\t\t\t<p>Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\tthe parent element, therefore the :hover pseudo class should be after .navbar-toggle \r\n");
      out.write("\t\t\t\tas opposed to the .icon-bar . In other words, you should use the selector .navbar-toggle:hover\r\n");
      out.write("\t\t\t\t .icon-bar .Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\t the parent element, therefore the :hover pseudo class should be after .navbar-toggle a\r\n");
      out.write("\t\t\t\t s opposed to the .icon-bar . In other words, you should use the selector \r\n");
      out.write("\t\t\t\t .navbar-toggle:hover .icon-bar .</p>\r\n");
      out.write("\t\t\t\t<p>Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\tthe parent element, therefore the :hover pseudo class should be after .navbar-toggle \r\n");
      out.write("\t\t\t\tas opposed to the .icon-bar . In other words, you should use the selector .navbar-toggle:hover\r\n");
      out.write("\t\t\t\t .icon-bar .Sep 6, 2014 - You are wanting to change the background color when hovering over \r\n");
      out.write("\t\t\t\t the parent element, therefore the :hover pseudo class should be after .navbar-toggle a\r\n");
      out.write("\t\t\t\t s opposed to the .icon-bar . In other words, you should use the selector \r\n");
      out.write("\t\t\t\t .navbar-toggle:hover .icon-bar .</p>\r\n");
      out.write("\t\t\t\t </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer class=\"container-fluid text-center\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<h3>Contact Us</h3>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<h4>Our Address & contact Info</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t<h3>Connect with Us!!!</h3>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"fa fa-facebook\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"fa fa-twitter\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"fa fa-google\"></a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"fa fa-linkedin\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t<img src=\"img/bunny.png\" class=\"icon\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>  \r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
